name: Deploy React App

on:
  push:
    branches: [ "main" ] # or "main" or any branch

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: CI=false npm run build

    - name: Deploy build
      run: |
        rm -rf /var/www/html/zentoken.live/*
        cp -r build/* /var/www/html/zentoken.live
